# Generated by Django 4.0.6 on 2022-08-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_items_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
