# Generated by Django 4.0.6 on 2022-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_kala'),
        ('CustomUser', '0004_remove_user_favorites_delete_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='shop.kala'),
        ),
    ]
