# Generated by Django 4.0.6 on 2022-08-01 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('website', models.CharField(max_length=120, verbose_name='website')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ClotheSizeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit', models.CharField(max_length=200, verbose_name='fit')),
                ('length', models.CharField(max_length=200, verbose_name='length ')),
                ('bust', models.CharField(blank=True, max_length=200, null=True, verbose_name='bust')),
                ('waist', models.CharField(blank=True, max_length=200, null=True, verbose_name='waist')),
                ('hip', models.CharField(blank=True, max_length=200, null=True, verbose_name='hip')),
                ('undergarments', models.CharField(blank=True, max_length=200, null=True, verbose_name='undergarments')),
                ('fabric', models.CharField(blank=True, max_length=200, null=True, verbose_name='fabric')),
            ],
            options={
                'verbose_name': 'Clothe Size Info',
                'verbose_name_plural': 'Clothe Size Info',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('color_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Hex code must be in the format #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='color code')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('percent', models.PositiveIntegerField(verbose_name='percent')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_expired', models.DateTimeField(blank=True, null=True, verbose_name='date expired')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/items/%Y/%m/%d', verbose_name='Image')),
                ('image_alt', models.CharField(max_length=200, null=True, verbose_name='Image alt')),
                ('image_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image name')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120, verbose_name='fist name')),
                ('lastname', models.CharField(max_length=120, verbose_name='last name')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('bust', models.PositiveIntegerField(verbose_name='bust')),
                ('waist', models.PositiveIntegerField(verbose_name='waist')),
                ('hip', models.PositiveIntegerField(verbose_name='hip')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SizeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('bust', models.CharField(max_length=20, verbose_name='bust')),
                ('waist', models.CharField(max_length=20, verbose_name='waist')),
                ('hip', models.CharField(max_length=20, verbose_name='hip')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
            options={
                'verbose_name': 'Size Choice',
                'verbose_name_plural': 'Size Choices',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('quantity', models.PositiveIntegerField(help_text='the number of items left in the stock', verbose_name='quantity')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('features', models.TextField(blank=True, help_text='insert each feature in one line', null=True, verbose_name='features')),
                ('rate', models.CharField(default='0', max_length=4, verbose_name='rate')),
                ('rate_count', models.IntegerField(default=0, verbose_name='rate count')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.brand', verbose_name='brand')),
                ('category', models.ManyToManyField(to='shop.category', verbose_name='category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.color', verbose_name='color')),
                ('images', models.ManyToManyField(to='shop.itemimage', verbose_name='images')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.models', verbose_name='model')),
                ('related', models.ManyToManyField(to='shop.item', verbose_name='related items')),
                ('sizeinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.clothesizeinfo')),
                ('sizes', models.ManyToManyField(to='shop.sizechoices', verbose_name='available sizes')),
            ],
        ),
    ]
