# Generated by Django 4.0.6 on 2022-08-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddField(
            model_name='item',
            name='specefic_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='specific color'),
        ),
        migrations.AlterField(
            model_name='clothesizeinfo',
            name='fit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='fit'),
        ),
        migrations.AlterField(
            model_name='clothesizeinfo',
            name='length',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='length '),
        ),
    ]
