# Generated by Django 4.0.6 on 2022-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_dress_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesizeinfo',
            name='quick_add',
            field=models.TextField(blank=True, help_text='add in the following format: <field name>:<value>.\nadd each field in one line', null=True, verbose_name='quick add'),
        ),
    ]
