# Generated by Django 4.0.6 on 2022-08-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_clothesizeinfo_quick_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, to='shop.dress', verbose_name='related items'),
        ),
    ]
