# Generated by Django 4.0.6 on 2022-08-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_dress_add_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='specefic_color',
            new_name='specific_color',
        ),
    ]
