# Generated by Django 4.0.6 on 2022-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_specefic_color_dress_specific_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='page title'),
        ),
    ]
