# Generated by Django 4.0.6 on 2022-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_dress_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/models/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='models',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image alt'),
        ),
    ]
