# Generated by Django 4.0.6 on 2022-08-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_models_image_models_image_alt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
