# Generated by Django 4.0.6 on 2022-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_kala'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='weight',
            field=models.CharField(default='0', help_text='Enter weight in grams', max_length=10, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='testitem',
            name='weight',
            field=models.CharField(default='0', help_text='Enter weight in grams', max_length=10, verbose_name='weight'),
        ),
    ]
