# Generated by Django 4.0.6 on 2022-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_alter_order_items_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True, default=dict, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
